# GirHub Workflow
name: Deployment of assignment2

run-name: Deploying resources for assignment 2

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  create_update_stack:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Cred
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Run cf deploy
        run: python3 stack.py
